
eureka:
  client:
    # 是否将自己注册在 EurekaServer 上，默认为 true。由于当前应用就是 EurekaClient，所以置为 true
    #fetch-registry: true

    # 是否将自己注册在 EurekaServer 上，默认为 true。由于当前应用是 EurekaClient，所以设置为 true
    #register-with-eureka: true

    service-url:
      # 将服务注册到 Eureka Serve 上
      defaultZone: http://localhost:8761/eureka

  instance:
    # Eureka 客户端的主机名
    hostname: eurekaClinetHostName

spring:
  application:
    name: client